#ifndef MARKET_DATA_HPP
#define MARKET_DATA_HPP

#include <string>
#include <vector>

#include <Eigen/Dense>

struct Asset
{
    std::string company;
    std::string ticker;
    std::string yfinanceTicker;

    double beta;
    double expectedReturn;
    double marketCapWeight;

    // total simple return this stock produced from the training end
    // date to today. Only meaningful when
    // MarketData::backtestAvailable is true.
    double forwardReturn;
};

struct MarketData
{
    std::vector<Asset> assets;

    Eigen::MatrixXd covariance;

    double riskFreeRate;
    double marketReturn;

    std::string startDate;
    std::string endDate;

    int years;
    int numberOfObservations;
    int tradingDaysPerYear;

    // true if a backtest period (endDate -> today) was generated by
    // stockinfo.py; if false, Asset::forwardReturn and
    // ftseForwardReturn are not meaningful
    bool backtestAvailable = false;

    std::string backtestStartDate;
    std::string backtestEndDate;

    double ftseForwardReturn = 0.0;

    // total cash return over the backtest period
    double backtestRiskFreeReturn = 0.0;

    // daily closing prices over the backtest period.
    // backtestPrices(t, i) = close of assets[i] on backtestDates[t]
    Eigen::MatrixXd backtestPrices;
    Eigen::VectorXd ftseBacktestPrices;
};

MarketData loadMarketData(
    const std::string& dataDirectory
);

#endif