#include <iostream>
#include <iomanip>
#include <vector>
#include <numeric>
#include <stdexcept>

#include "MarketData.hpp"
#include "Portfolio.hpp"


int main() {
    try {
        // loads data generated by Python
        MarketData marketData = loadMarketData("portfolio_data");

        const std::size_t n = marketData.assets.size();

        std::cout
            << "Portfolio optimiser\n"
            << "===================\n\n";

        std::cout
            << "Stocks loaded: "
            << n
            << '\n';

        std::cout
            << "Historical period: "
            << marketData.years
            << " years\n";

        std::cout
            << "Observations: "
            << marketData.numberOfObservations
            << '\n';

        std::cout
            << "Risk-free rate: "
            << std::fixed
            << std::setprecision(4)
            << marketData.riskFreeRate * 100.0
            << "%\n";

        std::cout
            << "Market return: "
            << marketData.marketReturn * 100.0
            << "%\n\n";

        // creates a simple test portfolio
        // every stock an equal weight and nothing in cash.

        Portfolio portfolio;

        portfolio.weights =
            std::vector<double>(n, 1.0 / static_cast<double>(n));

        portfolio.cashWeight = 0.0;

        // calculates portfolio metrics
        portfolio.expectedReturn =
            calculateExpectedReturn(portfolio, marketData);

        portfolio.volatility = calculateVolatility(portfolio, marketData);

        portfolio.sharpeRatio = calculateSharpeRatio(portfolio, marketData);


        // displays portfolio metrics
        std::cout
            << "Equal-weight portfolio\n"
            << "----------------------\n";

        std::cout
            << "Expected return: "
            << portfolio.expectedReturn * 100.0
            << "%\n";

        std::cout
            << "Volatility:       "
            << portfolio.volatility * 100.0
            << "%\n";

        std::cout
            << "Sharpe ratio:     "
            << portfolio.sharpeRatio
            << "\n";


        // tests the multi-objective fitness
        // arbitrary values for testing only

        double returnWeight = 0.3;
        double volatilityWeight = 0.2;
        double sharpeWeight = 0.5;

        double fitness =
            calculateFitness(
                portfolio,
                marketData,
                returnWeight,
                volatilityWeight,
                sharpeWeight
            );

        std::cout
            << "Fitness:          "
            << fitness
            << "\n";

        // checks the weights
        double totalWeight =
            std::accumulate(
                portfolio.weights.begin(),
                portfolio.weights.end(),
                0.0
            );

        totalWeight += portfolio.cashWeight;

        std::cout
            << "\nTotal portfolio weight: "
            << totalWeight
            << '\n';

        std::cout
            << "\nProgram completed successfully.\n";
    } catch (const std::exception& exception){
        std::cerr
            << "ERROR: "
            << exception.what()
            << '\n';

        return 1;
    }

    return 0;
}