#include <iostream>
#include <iomanip>
#include <vector>
#include <numeric>
#include <stdexcept>

#include "MarketData.hpp"
#include "Portfolio.hpp"
#include "GeneticAlgorithm.hpp"


int main() {
    try {
        // loads data generated by Python
        MarketData marketData = loadMarketData("portfolio_data");

        const std::size_t n = marketData.assets.size();

        std::cout
            << "Portfolio optimiser\n"
            << "===================\n\n";

        std::cout
            << "Stocks loaded: "
            << n
            << '\n';

        std::cout
            << "Historical period: "
            << marketData.years
            << " years\n";

        std::cout
            << "Observations: "
            << marketData.numberOfObservations
            << '\n';

        std::cout
            << "Risk-free rate: "
            << std::fixed
            << std::setprecision(4)
            << marketData.riskFreeRate * 100.0
            << "%\n";

        std::cout
            << "Market return: "
            << marketData.marketReturn * 100.0
            << "%\n\n";

        // user inputs

        GASettings settings;

        std::cout
            << "Genetic algorithm settings\n"
            << "--------------------------\n";

        std::cout << "Population size [500]: ";

        std::cin >> settings.populationSize;

        if (!std::cin) {
            settings.populationSize = 500;
            std::cin.clear();
        }

        std::cout << "Number of generations [500]: ";

        std::cin >> settings.generations;

        if (!std::cin) {
            settings.generations = 500;
            std::cin.clear();
        }

        // stock weight constraints

        std::cout
            << "\nStock weight constraints\n"
            << "------------------------\n";

        std::cout
            << "Minimum stock weight "
               "(e.g. -0.05): ";

        std::cin >> settings.minimumStockWeight;

        std::cout << "Maximum stock weight (e.g. 0.10): ";

        std::cin >> settings.maximumStockWeight;

        // objective weights

        std::cout
            << "\nObjective weights\n"
            << "-----------------\n";

        std::cout << "Expected return weight: ";

        std::cin >> settings.returnWeight;

        std::cout << "Volatility weight: ";

        std::cin >> settings.volatilityWeight;

        std::cout << "Sharpe ratio weight: ";

        std::cin >> settings.sharpeWeight;

        // GA parameters

        settings.mutationRate = 0.05;

        settings.mutationStrength = 0.02;

        settings.tournamentSize = 5;

        settings.eliteFraction = 0.05;

        // display settings

        std::cout << "\nRunning genetic algorithm...\n\n";

        std::cout
            << "Population: "
            << settings.populationSize
            << '\n';

        std::cout
            << "Generations: "
            << settings.generations
            << '\n';

        std::cout
            << "Minimum stock weight: "
            << settings.minimumStockWeight * 100.0
            << "%\n";

        std::cout
            << "Maximum stock weight: "
            << settings.maximumStockWeight * 100.0
            << "%\n";

        std::cout
            << "Return objective weight: "
            << settings.returnWeight
            << '\n';

        std::cout
            << "Volatility objective weight: "
            << settings.volatilityWeight
            << '\n';

        std::cout
            << "Sharpe objective weight: "
            << settings.sharpeWeight
            << "\n\n";

        // runs GA

        GeneticAlgorithm geneticAlgorithm(marketData, settings);

        Portfolio bestPortfolio = geneticAlgorithm.run();

        // displays result

        std::cout
            << "\nBest portfolio found\n"
            << "====================\n\n";

        std::cout
            << "Expected return: "
            << bestPortfolio.expectedReturn * 100.0
            << "%\n";

        std::cout
            << "Volatility:       "
            << bestPortfolio.volatility * 100.0
            << "%\n";

        std::cout
            << "Sharpe ratio:     "
            << bestPortfolio.sharpeRatio
            << '\n';

        std::cout
            << "Cash:             "
            << bestPortfolio.cashWeight
                * 100.0
            << "%\n";

        double fitness =
            calculateFitness(
                bestPortfolio,
                marketData,
                settings.returnWeight,
                settings.volatilityWeight,
                settings.sharpeWeight
            );

        std::cout
            << "Fitness:          "
            << fitness
            << "\n\n";

        // displays stock positions

        std::cout
            << "Portfolio holdings\n"
            << "------------------\n";

        for (std::size_t i = 0; i < marketData.assets.size(); ++i) {
            double weight =bestPortfolio.weights[i];


            // only displays positions which are
            // meaningfully different from zero

            if (std::abs(weight) > 0.0001)
            {
                std::cout
                    << std::setw(8)
                    << marketData.assets[i].ticker
                    << "  "
                    << std::setw(12)
                    << marketData.assets[i].company
                    << "  "
                    << std::fixed
                    << std::setprecision(4)
                    << weight * 100.0
                    << "%\n";
            }
        }

        std::cout << "\nProgram completed successfully.\n";
    } catch (const std::exception& exception) {
        std::cerr
            << "\nERROR: "
            << exception.what()
            << '\n';

        return 1;
    }

    return 0;
}